### ISSUE TITLE
issue while building for production.

### ISSUE THREAD

**Issue by dhirajbasukala** [patrikholcak/hot-loader-demo#2]
First of, kudos for providing a working hot reload with webpack 2. I have tired many others kits and this one worked, out of the box. The issue is while creating a  production build it won't minify the code, and I'm with almost 1MB production file.  I tried with webpack -p, webpack's default production built command, no success. I tried using webpack only and custom uglyfyjsplugin with compress:true only, still no success. While it build, I get 

`
D:\Code\hotloader>webpack
Hash: 05ebecc6b7f346ac962e
Version: webpack 2.1.0-beta.25
Time: 3012ms
  Asset    Size  Chunks             Chunk Names
main.js  893 kB       0  [emitted]  main
 [257] multi main 28 bytes {0} [built]
    + 257 hidden modules

ERROR in main.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [main.js:13261,19]
`

**Comment by patrikholcak** [comment]
Hey @dhirajbasukala, I just pushed a new commit which adds the build task (`npm run build`) and it uses `./webpack.config.prod.js`.

Check out [the config](https://github.com/patrikholcak/hot-loader-demo/blob/master/webpack.config.prod.js) — UglifyJS doesn’t understand ES6 yet, so I added some babel plugins to fix it. I went for the minimal setup, but you might want to edit the plugin list/move it to `.babelrc` or even use a preset instead of having to add to the list every time it breaks.

Cheers!
